name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      repository-projects: write
      packages: write

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: mvn-repo
          settings-path: ${{ github.workspace }}

      - name: Maven Release x GitHub Packages
        run: |
          git config --global user.name "rtx-inspire"
          git config --global user.email "inspiringfacts57@gmail.com"
          mvn release:prepare --batch-mode 
          mvn release:perform -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}