name: Release on Tag

on:
  repository_dispatch:
    types: [trigger-release]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.event.client_payload.tag_name }}
          release_name: Release ${{ github.event.client_payload.tag_name }}
          draft: false
          prerelease: false

      - name: Publish to GitHub Packages
        run: mvn -s $GITHUB_WORKSPACE/settings.xml deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
