name: Release on Tag

on:
  workflow_run:
    workflows: ["Maven Package"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Latest Tag Version
        id: get_tag_version
        run: echo ::set-output name=TAG_VERSION::$(git describe --tags --abbrev=0 | sed 's/v//')

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ steps.get_tag_version.outputs.TAG_VERSION }}
          release_name: Release ${{ steps.get_tag_version.outputs.TAG_VERSION }}
          draft: false
          prerelease: false
